/**
 * Local AI Content Detector Utility
 * 
 * This tool detects if a piece of text was likely generated by an AI (LLM) 
 * using statistical analysis (Burstiness and Perplexity) entirely locally.
 * 
 * Works without any API calls.
 */

export interface AIDetectionResult {
  isAI: boolean;
  confidence: number;
  burstiness: number;
  perplexity: number;
  reason: string;
}

export function detectAIContent(text: string): AIDetectionResult {
  if (!text || text.trim().length < 50) {
    return {
      isAI: false,
      confidence: 0,
      burstiness: 0,
      perplexity: 0,
      reason: "Text too short for reliable analysis (minimum 50 characters)."
    };
  }

  // 1. BURSTINESS ANALYSIS (Sentence length variance)
  // AI models tend to produce sentences of consistent, moderate length.
  // Human writers have high variance (some very short, some long).
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
  const sentenceLengths = sentences.map(s => s.trim().split(/\s+/).length);
  
  const avgLength = sentenceLengths.reduce((a, b) => a + b, 0) / sentenceLengths.length;
  const variance = sentenceLengths.reduce((a, b) => a + Math.pow(b - avgLength, 2), 0) / sentenceLengths.length;
  const burstiness = Math.sqrt(variance);

  // 2. PERPLEXITY SIMULATION (Word randomness)
  // AI uses highly predictable "top-prob" words.
  // We check for common AI transitional phrases and "perfect" grammar.
  const aiPhrases = [
    'in conclusion', 'it is important to note', 'moreover', 'furthermore', 
    'as an ai', 'certainly', 'i hope this helps', 'firstly', 'secondly',
    'comprehensive', 'tailored', 'designed to', 'ensure'
  ];
  
  let phraseCount = 0;
  const lowerText = text.toLowerCase();
  aiPhrases.forEach(p => {
    if (lowerText.includes(p)) phraseCount++;
  });

  // 3. VOCABULARY DIVERSITY (Type-Token Ratio)
  const words = text.toLowerCase().match(/\b(\w+)\b/g) || [];
  const uniqueWords = new Set(words);
  const ttr = words.length > 0 ? (uniqueWords.size / words.length) : 0;

  // 4. SCORING LOGIC
  // Low Burstiness (< 3) + Low TTR (< 0.5) + AI Phrases (> 2) = High AI Likelihood
  let score = 0;
  
  // Burstiness component: Lower burstiness = more likely AI
  if (burstiness < 3) score += 0.4;
  else if (burstiness < 5) score += 0.2;
  
  // AI Phrases component
  if (phraseCount >= 3) score += 0.3;
  else if (phraseCount >= 1) score += 0.1;

  // Predictability/TTR
  if (ttr < 0.4) score += 0.2;

  // 5. FINAL RESULT
  const confidence = Math.min(0.95, score);
  const isAI = confidence > 0.6;

  let reason = "";
  if (isAI) {
    reason = `High predictability and low sentence variance (Burstiness: ${burstiness.toFixed(2)}) suggest AI generation.`;
  } else if (confidence > 0.3) {
    reason = "Mixed signals detected. The text appears balanced but contains some repetitive patterns.";
  } else {
    reason = "High sentence variance and diverse vocabulary suggest human authorship.";
  }

  return {
    isAI,
    confidence,
    burstiness,
    perplexity: ttr * 100, // Normalized TTR as perplexity proxy
    reason
  };
}
